import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/Navbar/NavBar";

const GeneralSansMedium = localFont({
  src: "font/GeneralSans-Medium.woff2",
  variable: "--font-generalsans-medium",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeneralSansMedium.className} antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
