import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/Navbar/NavBar";

const GeneralSans = localFont({
  src: "font/GeneralSans-Regular.woff2",
  variable: "--font-generalsans",
});

const GeneralSansMedium = localFont({
  src: "font/GeneralSans-Medium.woff2",
  variable: "--font-generalsans-medium",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${GeneralSansMedium.className} `}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
